import type { ThemeConfig } from "../../../types/types";


export const themeConfigs: Record<string, ThemeConfig> = {
  "modern-ats": {
    id: "modern-ats",
    name: "Modern ATS",
    layout: "ats",
    primaryColor: "#2563eb",
    secondaryColor: "#64748b",
    accentColor: "#dbeafe",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  "simple-ats": {
    id: "simple-ats",
    name: "Simple ATS",
    layout: "ats",
    primaryColor: "#111827",
    secondaryColor: "#6b7280",
    accentColor: "#f3f4f6",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Times New Roman",
  },

  "professional-ats": {
    id: "professional-ats",
    name: "Professional ATS",
    layout: "ats",
    primaryColor: "#0f766e",
    secondaryColor: "#475569",
    accentColor: "#ccfbf1",
    textColor: "#0f172a",
    backgroundColor: "#ffffff",
    fontFamily: "Georgia",
  },

  "executive-ats": {
    id: "executive-ats",
    name: "Executive ATS",
    layout: "ats",
    primaryColor: "#1e3a8a",
    secondaryColor: "#475569",
    accentColor: "#dbeafe",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Georgia",
  },

  "blue-corporate": {
    id: "blue-corporate",
    name: "Blue Corporate",
    layout: "corporate",
    primaryColor: "#1d4ed8",
    secondaryColor: "#475569",
    accentColor: "#eff6ff",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  "black-executive": {
    id: "black-executive",
    name: "Black Executive",
    layout: "corporate",
    primaryColor: "#111827",
    secondaryColor: "#4b5563",
    accentColor: "#f3f4f6",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Georgia",
  },

  "finance-professional": {
    id: "finance-professional",
    name: "Finance Professional",
    layout: "corporate",
    primaryColor: "#047857",
    secondaryColor: "#475569",
    accentColor: "#ecfdf5",
    textColor: "#064e3b",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  "legal-professional": {
    id: "legal-professional",
    name: "Legal Professional",
    layout: "corporate",
    primaryColor: "#7c2d12",
    secondaryColor: "#57534e",
    accentColor: "#fff7ed",
    textColor: "#1c1917",
    backgroundColor: "#ffffff",
    fontFamily: "Georgia",
  },

  designer: {
    id: "designer",
    name: "Designer",
    layout: "creative",
    primaryColor: "#db2777",
    secondaryColor: "#6b7280",
    accentColor: "#fce7f3",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  marketing: {
    id: "marketing",
    name: "Marketing",
    layout: "creative",
    primaryColor: "#ea580c",
    secondaryColor: "#475569",
    accentColor: "#ffedd5",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  "ui-ux": {
    id: "ui-ux",
    name: "UI UX",
    layout: "creative",
    primaryColor: "#7c3aed",
    secondaryColor: "#64748b",
    accentColor: "#ede9fe",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  "creative-portfolio": {
    id: "creative-portfolio",
    name: "Creative Portfolio",
    layout: "creative",
    primaryColor: "#0891b2",
    secondaryColor: "#475569",
    accentColor: "#cffafe",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  "developer-pro": {
    id: "developer-pro",
    name: "Developer Pro",
    layout: "technical",
    primaryColor: "#4f46e5",
    secondaryColor: "#475569",
    accentColor: "#eef2ff",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Consolas",
  },

  "engineer-pro": {
    id: "engineer-pro",
    name: "Engineer Pro",
    layout: "technical",
    primaryColor: "#0369a1",
    secondaryColor: "#475569",
    accentColor: "#e0f2fe",
    textColor: "#0f172a",
    backgroundColor: "#ffffff",
    fontFamily: "Arial",
  },

  "full-stack": {
    id: "full-stack",
    name: "Full Stack",
    layout: "technical",
    primaryColor: "#059669",
    secondaryColor: "#475569",
    accentColor: "#d1fae5",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Consolas",
  },

  devops: {
    id: "devops",
    name: "DevOps",
    layout: "technical",
    primaryColor: "#0f172a",
    secondaryColor: "#64748b",
    accentColor: "#e2e8f0",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Consolas",
  },

  "luxury-black": {
    id: "luxury-black",
    name: "Luxury Black",
    layout: "premium",
    primaryColor: "#111827",
    secondaryColor: "#d1d5db",
    accentColor: "#facc15",
    textColor: "#f9fafb",
    backgroundColor: "#030712",
    fontFamily: "Georgia",
  },

  "gold-executive": {
    id: "gold-executive",
    name: "Gold Executive",
    layout: "premium",
    primaryColor: "#92400e",
    secondaryColor: "#78350f",
    accentColor: "#fef3c7",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Georgia",
  },

  "minimal-premium": {
    id: "minimal-premium",
    name: "Minimal Premium",
    layout: "premium",
    primaryColor: "#374151",
    secondaryColor: "#6b7280",
    accentColor: "#f3f4f6",
    textColor: "#111827",
    backgroundColor: "#ffffff",
    fontFamily: "Inter",
  },
};