export const INDIAN_DEGREES = [
  "10th Standard (SSC / CBSE / ICSE)",
  "12th Standard (HSC / CBSE / ISC)",
  "Diploma in Engineering",
  "Bachelor of Technology (B.Tech)",
  "Bachelor of Engineering (B.E.)",
  "Bachelor of Computer Applications (BCA)",
  "Bachelor of Science (B.Sc)",
  "Bachelor of Commerce (B.Com)",
  "Bachelor of Business Administration (BBA)",
  "Bachelor of Arts (B.A.)",
  "Bachelor of Architecture (B.Arch)",
  "Bachelor of Pharmacy (B.Pharm)",
  "Bachelor of Design (B.Des)",
  "Bachelor of Medicine, Bachelor of Surgery (MBBS)",
  "Bachelor of Laws (LL.B.)",
  "Master of Technology (M.Tech)",
  "Master of Computer Applications (MCA)",
  "Master of Science (M.Sc)",
  "Master of Business Administration (MBA)",
  "Master of Commerce (M.Com)",
  "Master of Arts (M.A.)",
  "Master of Pharmacy (M.Pharm)",
  "Master of Laws (LL.M.)",
  "Doctor of Philosophy (Ph.D.)",
];
